defaults:
  -
    scope:
      path: "guides"
    values:
      layout: "guides"
  -
    scope:
      path: "projects"
    values:
      layout: "projects"
include: [README.md,CONTRIBUTING.md]
permalink: pretty

# Use the amsterdam-jekyll-theme from https://github.com/Amsterdam/amsterdam-jekyll-theme
remote_theme: amsterdam/amsterdam-jekyll-theme
headerHideTitle: true
